### PR TITLE
fix(error): replace unwraps with ? or expect

### LINKED ISSUE #21: Remove all `unwrap`s
These were good for prototyping, but we should get rid of them.

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #21

### CODE REVIEW

**Comment by steveklabnik** [comment]
There are a few of these left, but this is what's practical for now.

File: src/error.rs [hunk 1]
```diff
@@ -0,0 +1,35 @@
+use std;
+use http;
+use httparse;
+
+#[derive(Debug)]
+pub enum Error {
+  Io(std::io::Error),
```
Comment (steveklabnik) [inline src/error.rs]: run rustfmt please!
